const RespErrCode = {
    e301: 'CLIENT_SESSION_TIMEOUT_ERROR',
    e401: 'ERROR_OCCURED_IN_HTTP_PARAMS_CHECK',
    e502: 'ERROR_OCCURED_IN_GET_DATA_SOURCE',
    e503: 'ERROR_OCCURED_IN_BUSINESS_PROCEDURE',
    e801: 'BACK_END_ROUTE_NOT_AUTHORISED_ERROR'
};
